// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKYnwxbQ7Hsv2wDxlCuULN_GfF0_TjbxQ',
    appId: '1:1008935946269:android:2cd355c3ce1c6de8db5ef4',
    messagingSenderId: '1008935946269',
    projectId: 'eramex-3ffe9',
    storageBucket: 'eramex-3ffe9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWRZNg8dlWW6iz_rA1QsHnZZv9y3FaVAI',
    appId: '1:1008935946269:ios:8021f58c5167af7fdb5ef4',
    messagingSenderId: '1008935946269',
    projectId: 'eramex-3ffe9',
    storageBucket: 'eramex-3ffe9.firebasestorage.app',
    iosBundleId: 'com.eramgroupsa.express.eramExpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWRZNg8dlWW6iz_rA1QsHnZZv9y3FaVAI',
    appId: '1:1008935946269:ios:cb79fc805ace9562db5ef4',
    messagingSenderId: '1008935946269',
    projectId: 'eramex-3ffe9',
    storageBucket: 'eramex-3ffe9.firebasestorage.app',
    iosBundleId: 'com.eramgroupsa.expres',
  );
}
